#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MissedCallText.Resource", IsApplication=true)]

namespace MissedCallText
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_stat_name = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int forwardNumber = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int sendSMS = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int setForward = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int startService = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int stopService = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int app_description = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int forwardNumTitle = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int get_timestamp_button_text = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int manualStartService = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int manualStopService = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int restart_timestamp_service_button_text = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int sendSMSTitle = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int service_not_connected = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int service_started = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int stop_timestamp_service_button_text = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
